# Generated by Django 5.0 on 2024-02-18 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funnytail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cats",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="cats",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="funnytail.breed",
                verbose_name="Порода",
            ),
        ),
        migrations.AddIndex(
            model_name="tagposts",
            index=models.Index(fields=["tag"], name="funnytail_t_tag_5f9c09_idx"),
        ),
        migrations.AddField(
            model_name="cats",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="funnytail.tagposts",
                verbose_name="Теги",
            ),
        ),
        migrations.AddIndex(
            model_name="cats",
            index=models.Index(fields=["title"], name="funnytail_c_title_9c7fc1_idx"),
        ),
    ]
