# Generated by Django 5.0 on 2024-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='cats',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='cats',
            index=models.Index(fields=['title'], name='funnytail_c_title_9c7fc1_idx'),
        ),
    ]
