# Generated by Django 5.0 on 2024-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0002_alter_cats_options_cats_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
