# Generated by Django 5.0 on 2024-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0003_alter_cats_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
