# Generated by Django 5.0 on 2024-02-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0005_breed_cats_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funnytail.breed'),
        ),
    ]
