# Generated by Django 5.0 on 2024-02-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0006_alter_cats_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='funnytail.breed'),
        ),
        migrations.AddField(
            model_name='cats',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='funnytail.tagposts'),
        ),
    ]
