# Generated by Django 5.0 on 2024-02-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0007_tagposts_alter_cats_breed_cats_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='funnytail.tagposts'),
        ),
    ]
