# Generated by Django 5.0 on 2024-02-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnytail', '0008_alter_cats_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='cats',
            options={'ordering': ['title'], 'verbose_name': 'Кошки', 'verbose_name_plural': 'Кошки'},
        ),
        migrations.AlterModelOptions(
            name='tagposts',
            options={'ordering': ['tag']},
        ),
        migrations.AddField(
            model_name='cats',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='funnytail.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='funnytail.tagposts', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создание'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Кличка'),
        ),
        migrations.AddIndex(
            model_name='tagposts',
            index=models.Index(fields=['tag'], name='funnytail_t_tag_5f9c09_idx'),
        ),
    ]
